name: Deploy Web Dashboard

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'

    # Install Poetry
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

    # Install dependencies
    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-root

    # Run benchmark suite
    - name: Run benchmarks and generate results
      run: |
        poetry run python main.py

    # Prepare web data
    - name: Prepare web data and images
      run: |
        bash scripts/prepare_web_data.sh

    # Deploy web to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web
        publish_branch: gh-pages
